---
abstract: 'Directory based Location Handler helper'
author:
  - 'Adam Prime (adam.prime@utoronto.ca)'
build_requires:
  Apache::Test: '1.12'
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.422, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Apache2-DirBasedHandler
provides:
  Apache2::DirBasedHandler:
    file: lib/Apache2/DirBasedHandler.pm
    version: '0.04'
requires:
  Apache2::Request: '2'
  mod_perl2: '2'
resources:
  license: http://dev.perl.org/licenses/
version: '0.04'
x_serialization_backend: 'CPAN::Meta::YAML version 0.012'
